name: Release
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: jasonkarns/create-release@master

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: nodenv-auto-install
          homebrew-tap: manlao/homebrew-tap
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
